In [5]:
import pandas as pd
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive')

Mounted at /content/drive

In [13]:
import pandas as pd
from google.colab import drive

# Montar Google Drive
drive.mount('/content/drive', force_remount=True)

# Lista de arquivos e abas
files = {
    '2019': '/content/drive/MyDrive/Dados TCC/VendasEtanol/2019-vendas-etanol.xlsx',
    '2020': '/content/drive/MyDrive/Dados TCC/VendasEtanol/2020-vendas-etanol.xlsx',
    '2021': '/content/drive/MyDrive/Dados TCC/VendasEtanol/2021-vendas-etanol.xlsx',
    '2022': '/content/drive/MyDrive/Dados TCC/VendasEtanol/2022-vendas-etanol.xlsx',
    '2023': '/content/drive/MyDrive/Dados TCC/VendasEtanol/2023-vendas-etanol.xlsx'
}

sheets = ['Anidro_Região', 'Hidratado_Região']

# Função para processar cada arquivo e aba
def process_file(file_path, year):
    data_anidro = pd.read_excel(file_path, sheet_name='Anidro_Região')
    data_hidratado = pd.read_excel(file_path, sheet_name='Hidratado_Região')

    # Remover a coluna 'Total Geral'
    if 'Total Geral' in data_anidro.columns:
        data_anidro = data_anidro.loc[:, data_anidro.columns != 'Total Geral']
    if 'Total Geral' in data_hidratado.columns:
        data_hidratado = data_hidratado.loc[:, data_hidratado.columns != 'Total Geral']

    # Transformar os dados de wide para long
    data_anidro = data_anidro.melt(var_name='mes', value_name='vendas')
    data_hidratado = data_hidratado.melt(var_name='mes', value_name='vendas')

    # Adicionar colunas de identificação do produto e ano
    data_anidro['produto'] = 'anidro'
    data_hidratado['produto'] = 'hidratado'

    # Converter vendas para float
    data_anidro['vendas'] = data_anidro['vendas'].astype(float)
    data_hidratado['vendas'] = data_hidratado['vendas'].astype(float)

    # Manter apenas as colunas relevantes
    data_anidro = data_anidro[['mes', 'vendas', 'produto']]
    data_hidratado = data_hidratado[['mes', 'vendas', 'produto']]

    return pd.concat([data_anidro, data_hidratado])


# DataFrame vazio para consolidar os dados
consolidated_data = pd.DataFrame()

# Processar todos os arquivos
for year, file_path in files.items():
    consolidated_data = pd.concat([consolidated_data, process_file(file_path, year)], ignore_index=True)

# Exportar para CSV
output_path = '/content/drive/MyDrive/Dados TCC/vendas_etanol_consolidado.csv'
consolidated_data.to_csv(output_path, index=False)

# Verificação de leitura
print(consolidated_data.head())

Mounted at /content/drive
         mes      vendas produto
0 2019-01-01  488479.725  anidro
1 2019-02-01  485485.438  anidro
2 2019-03-01  546250.992  anidro
3 2019-04-01  386844.810  anidro
4 2019-05-01  509214.653  anidro

In [16]:
# Verificação de leitura
print(consolidated_data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   mes      120 non-null    datetime64[ns]
 1   vendas   120 non-null    float64
 2   produto  120 non-null    object
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 2.9+ KB
None